# Generated by Django 4.0.4 on 2022-12-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
