# Generated by Django 4.0.4 on 2022-12-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_brand_alter_product_diameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
