# Generated by Django 4.0.4 on 2023-02-21 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_subimgs'),
        ('store', '0008_product_country'),
    ]

    operations = [
    ]
