# Generated by Django 4.0.4 on 2023-01-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='terrain',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
