# Generated by Django 4.0.4 on 2023-02-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_merge_0003_product_subimgs_0008_product_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ah',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='cca',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
