# Generated by Django 4.0.4 on 2023-01-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_discount_product_skuno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='skuno',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
