# Generated by Django 4.0.4 on 2023-01-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
