# Generated by Django 4.0.4 on 2022-12-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order_pos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
